### ISSUE TITLE
Ability to cc/bcc?

### ISSUE THREAD

**Issue by georgiosd** [RoushTech/SparkPostDotNet#19]
I guess it's not implemented? If I send you a PR, will you publish a new nuget?

**Comment by StrangeWill** [comment]
Well we use Transmissions (https://developers.sparkpost.com/api/transmissions.html) which are used for mass mailing, CC/BCC should have no affect (AFAIK: not supported on transmissions) because having multiple receipts shouldn't put them all in the "to" list, but individually mailed with each one as a single recipient.

We do _not_ currently support the basic SMTP API though, where TO/CC/BCC makes more sense, if you wanted to implement that, of course we'll accept a PR for that (and of course push that out to NuGet). :D 


I would be interested in the use case though were transmissions weren't good enough for this (unless the requirement is that you do see everyone that is in the recipient list).

**Comment by georgiosd** [comment]
That's where I looked too! See section "Request: Create Transmission Using CC Header" - seems to support it ok, no?

Basically I am trying to send a copy of the outgoing emails to ourselves.

I added the CC in the headers collection as in the example but I got interrupted so I'm not sure if it works yet :S

**Comment by StrangeWill** [comment]
Ah yeah, using the header section, didn't consider that!

You should be able to currently do this without changing the library:

```
transmission.Content.Headers = new
{
    cc = "myemail@example.com",
    bcc = "someother@example.com"
};
```

Though _maybe_ we should move to a `Dictionary<string, object>` instead of an `object`, but due to it being the SMTP header that we're tampering with I shy away from implementing a strongly typed object (because you can specify your own custom headers). We could do some weird hybrid object like we have prototyped in SegmentDotNet here: https://github.com/StrangeWill/SegmentDotNet/blob/release/0.1.0/src/SegmentDotNet/PropertyContainers/Serializers/PropertyContainerBaseSerializer.cs).

Let me know if you'd rather this be implemented a different way. I know it's not _intuitive_ but I can't think of a nice way to make header tampering both intuitive _and_ as flexible as it needs to be without doing the same we do in our SegmentDotNet stuff (which I wouldn't mind breaking out if it makes sense, it's just not tested much).

**Comment by georgiosd** [comment]
Frankly I'm happy with a `Dictionary` :)

Maybe include an example.

The full framework SparkPost C# SDK adds a `Type` enum attribute (To|Cc|Bcc) and handles it internally. But as long as I can find it, I don't particularly care :)

**Comment by StrangeWill** [comment]
I'll go check out their implementation. For the most part our `Content` class is just a POCO, but I don't mind making it more feature-rich.


The anonymous object above should work for now. We _may_ change it to a dictionary in the future. Let me know if that doesn't work for you though and I'll look into it.

**Comment by georgiosd** [comment]
Sure :)

Thanks!

**Comment by georgiosd** [comment]
We got busted.

CC works like we discussed. For BCC you must add to list of recipients and it doesn't really work like BCC (the TO: address doesn't appear).

Poop.

**Comment by georgiosd** [comment]
Would you kindly merge https://github.com/RoushTech/SparkPostDotNet/pull/20 and updated the nuget?

**Comment by StrangeWill** [comment]
Cool, yeah, give me a moment, I'll get it out today/tomorrow.

**Comment by georgiosd** [comment]
Thank you @StrangeWill !

**Comment by StrangeWill** [comment]
@georgiosd 0.3.0 is out here: https://www.nuget.org/packages/SparkPostDotNet/0.3.0

**Comment by georgiosd** [comment]
You're the man! Thanks

**Comment by StrangeWill** [comment]
No problem, and thanks for the PR. :D

**Comment by georgiosd** [comment]
Short and sweet :P
